trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build'
  steps:
  - checkout: self

  # Build steps
  - script: |
      # Commands to build your project
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      ArtifactName: 'drop'

- job: Deploy
  displayName: 'Deploy to staging'
  dependsOn: Build
  steps:
  - checkout: self

  # Deployment steps
  - script: |
      # Commands to deploy your application
    displayName: 'Deploy to staging'

  # Notification task on failure
  - script: |
      curl -X POST -H "Content-Type: application/json" -d '{
        "type": "message",
        "attachments": [
          {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
              "type": "AdaptiveCard",
              "body": [
                {
                  "type": "TextBlock",
                  "text": "Deployment to staging failed! Check the pipeline logs for details.",
                  "wrap": true
                }
              ],
              "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "version": "1.2"
            }
          }
        ]
      }' "https://teams.microsoft.com/l/team/19%3A5IWmdyIDR8hfWwOUsx3A6QAhMauukb6O7bmczKTUXsA1%40thread.tacv2/conversations?groupId=76933b95-aa4e-479e-a6f8-d4122f92e4d6&tenantId=f5ea3467-a1df-4d7e-a894-9a0c66d9b19e"
    displayName: 'Send Teams Notification'
    condition: failed()
